-- Patch v2: Create TEST_STEP and TEST_SEARCH_INDEX using dynamic SQL to avoid SQL*Plus parsing issues
SET DEFINE OFF;

-- Drop if exists (safe)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TEST_STEP CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TEST_SEARCH_INDEX CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; 
/

-- Create TEST_STEP via dynamic SQL
DECLARE
  ddl CLOB;
BEGIN
  ddl := 'CREATE TABLE TEST_STEP (
    STEP_ID NUMBER PRIMARY KEY,
    SCENARIO_ID NUMBER NOT NULL,
    CASE_NO VARCHAR2(10) NOT NULL,
    STEP_ORDER NUMBER NOT NULL,
    PRIORITY VARCHAR2(20) DEFAULT ''보통'',
    REQUEST_JSON CLOB NOT NULL,
    EXPECTED_JSON CLOB NOT NULL,
    TRANSACTION_TYPE VARCHAR2(50),
    REQUEST_METHOD VARCHAR2(50),
    CANCEL_YN CHAR(1),
    EXPECTED_RESPONSE_CODE VARCHAR2(10),
    EXPECTED_RESPONSE_MSG VARCHAR2(200),
    AMOUNT NUMBER(15,2),
    VERSION_STATUS VARCHAR2(20) DEFAULT ''DRAFT'',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_STEP_SCENARIO FOREIGN KEY (SCENARIO_ID) REFERENCES TEST_SCENARIO(SCENARIO_ID) ON DELETE CASCADE
  )';
  EXECUTE IMMEDIATE ddl;
END;
/

-- Indexes
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_STEP_SCENARIO ON TEST_STEP(SCENARIO_ID, STEP_ORDER)'; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_STEP_CASE_NO ON TEST_STEP(CASE_NO)'; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_STEP_PRIORITY ON TEST_STEP(PRIORITY, VERSION_STATUS)'; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_STEP_TRANSACTION ON TEST_STEP(TRANSACTION_TYPE, VERSION_STATUS)'; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_STEP_RESPONSE_CODE ON TEST_STEP(EXPECTED_RESPONSE_CODE)'; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_STEP_CANCEL ON TEST_STEP(CANCEL_YN, VERSION_STATUS)'; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_STEP_SEARCH_COMBO ON TEST_STEP(TRANSACTION_TYPE, EXPECTED_RESPONSE_CODE, VERSION_STATUS)'; END;
/
-- Comments
BEGIN EXECUTE IMMEDIATE 'COMMENT ON TABLE TEST_STEP IS ''테스트 스텝 (하이브리드: 정규화 + JSON)'''; END;
/
BEGIN EXECUTE IMMEDIATE 'COMMENT ON COLUMN TEST_STEP.TRANSACTION_TYPE IS ''REQUEST_JSON에서 추출된 거래방법 (검색 최적화)'''; END;
/
BEGIN EXECUTE IMMEDIATE 'COMMENT ON COLUMN TEST_STEP.EXPECTED_RESPONSE_CODE IS ''EXPECTED_JSON에서 추출된 응답코드 (검색 최적화)'''; END;
/
-- TEST_SEARCH_INDEX
DECLARE
  ddl2 CLOB;
BEGIN
  ddl2 := 'CREATE TABLE TEST_SEARCH_INDEX (
    INDEX_ID NUMBER PRIMARY KEY,
    STEP_ID NUMBER NOT NULL,
    CASE_ID NUMBER NOT NULL,
    FIELD_NAME VARCHAR2(100) NOT NULL,
    FIELD_VALUE VARCHAR2(1000) NOT NULL,
    VALUE_TYPE VARCHAR2(20),
    SOURCE_TYPE VARCHAR2(20),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SEARCH_STEP FOREIGN KEY (STEP_ID) REFERENCES TEST_STEP(STEP_ID) ON DELETE CASCADE
  )';
  EXECUTE IMMEDIATE ddl2;
END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TEST_SEARCH_INDEX START WITH 1 INCREMENT BY 1 CACHE 1000'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_SEARCH_FIELD_VALUE ON TEST_SEARCH_INDEX(FIELD_NAME, FIELD_VALUE)'; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_SEARCH_VALUE ON TEST_SEARCH_INDEX(FIELD_VALUE)'; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_SEARCH_CASE ON TEST_SEARCH_INDEX(CASE_ID)'; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_SEARCH_STEP ON TEST_SEARCH_INDEX(STEP_ID)'; END;
/
BEGIN EXECUTE IMMEDIATE 'COMMENT ON TABLE TEST_SEARCH_INDEX IS ''검색 최적화용 역인덱스 테이블'''; END;
/
BEGIN EXECUTE IMMEDIATE 'COMMENT ON COLUMN TEST_SEARCH_INDEX.FIELD_NAME IS ''JSON 내 필드명 (거래방법, 응답코드 등)'''; END;
/
BEGIN EXECUTE IMMEDIATE 'COMMENT ON COLUMN TEST_SEARCH_INDEX.FIELD_VALUE IS ''실제 값 (A, 0000 등)'''; END;
/
-- Verify
SET SERVEROUTPUT ON;
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'TEST_STEP';
  DBMS_OUTPUT.PUT_LINE('TEST_STEP exists: '||v_cnt);
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'TEST_SEARCH_INDEX';
  DBMS_OUTPUT.PUT_LINE('TEST_SEARCH_INDEX exists: '||v_cnt);
END;
/
