-- Patch: Simple TEST_STEP with JSON only (no normalized columns)
SET DEFINE OFF;

-- Drop if exists
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TEST_STEP CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TEST_SEARCH_INDEX CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; 
/

-- Create TEST_STEP (JSON only, no normalized columns)
DECLARE
  ddl CLOB;
BEGIN
  ddl := 'CREATE TABLE TEST_STEP (
    STEP_ID NUMBER PRIMARY KEY,
    SCENARIO_ID NUMBER NOT NULL,
    CASE_NO VARCHAR2(10) NOT NULL,
    STEP_ORDER NUMBER NOT NULL,
    PRIORITY VARCHAR2(20) DEFAULT ''보통'',
    REQUEST_JSON CLOB NOT NULL,
    EXPECTED_JSON CLOB NOT NULL,
    VERSION_STATUS VARCHAR2(20) DEFAULT ''DRAFT'',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_STEP_SCENARIO FOREIGN KEY (SCENARIO_ID) REFERENCES TEST_SCENARIO(SCENARIO_ID) ON DELETE CASCADE
  )';
  EXECUTE IMMEDIATE ddl;
END;
/

-- Basic indexes only
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_STEP_SCENARIO ON TEST_STEP(SCENARIO_ID, STEP_ORDER)'; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_STEP_CASE_NO ON TEST_STEP(CASE_NO)'; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_STEP_PRIORITY ON TEST_STEP(PRIORITY, VERSION_STATUS)'; END;
/

COMMENT ON TABLE TEST_STEP IS '테스트 스텝 (순수 JSON 저장)';

-- TEST_SEARCH_INDEX (optional, for dynamic field search)
DECLARE
  ddl2 CLOB;
BEGIN
  ddl2 := 'CREATE TABLE TEST_SEARCH_INDEX (
    INDEX_ID NUMBER PRIMARY KEY,
    STEP_ID NUMBER NOT NULL,
    CASE_ID NUMBER NOT NULL,
    FIELD_NAME VARCHAR2(100) NOT NULL,
    FIELD_VALUE VARCHAR2(1000) NOT NULL,
    VALUE_TYPE VARCHAR2(20),
    SOURCE_TYPE VARCHAR2(20),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SEARCH_STEP FOREIGN KEY (STEP_ID) REFERENCES TEST_STEP(STEP_ID) ON DELETE CASCADE
  )';
  EXECUTE IMMEDIATE ddl2;
END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TEST_SEARCH_INDEX START WITH 1 INCREMENT BY 1 CACHE 1000'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_SEARCH_FIELD_VALUE ON TEST_SEARCH_INDEX(FIELD_NAME, FIELD_VALUE)'; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_SEARCH_VALUE ON TEST_SEARCH_INDEX(FIELD_VALUE)'; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_SEARCH_CASE ON TEST_SEARCH_INDEX(CASE_ID)'; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_SEARCH_STEP ON TEST_SEARCH_INDEX(STEP_ID)'; END;
/

COMMENT ON TABLE TEST_SEARCH_INDEX IS '동적 필드 검색용 역인덱스 테이블';

-- Verify
SET SERVEROUTPUT ON;
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'TEST_STEP';
  DBMS_OUTPUT.PUT_LINE('TEST_STEP exists: '||v_cnt);
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'TEST_SEARCH_INDEX';
  DBMS_OUTPUT.PUT_LINE('TEST_SEARCH_INDEX exists: '||v_cnt);
END;
/
