-- ========================================
-- Oracle DB 스키마 설계 (대용량 최적화)
-- 버전 관리 + txt 마이그레이션 + 검색 성능 최적화
-- 대상: 70,000+ 테스트 케이스
-- ========================================

-- 1. 테스트 케이스 (파일 단위)
CREATE TABLE TEST_CASE (
    CASE_ID NUMBER PRIMARY KEY,
    FILE_NAME VARCHAR2(255) NOT NULL UNIQUE,
    TITLE VARCHAR2(500) NOT NULL,
    NOTE CLOB,
    VERSION_STATUS VARCHAR2(20) DEFAULT 'DRAFT',  -- DRAFT, PUBLISHED
    VERSION_NUMBER NUMBER DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR2(100) DEFAULT 'system',
    UPDATED_BY VARCHAR2(100) DEFAULT 'system'
);

CREATE SEQUENCE SEQ_TEST_CASE START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE TEST_CASE IS '테스트 케이스 메타 정보 (파일 단위)';
COMMENT ON COLUMN TEST_CASE.VERSION_STATUS IS 'DRAFT: 임시저장, PUBLISHED: 최종저장';
COMMENT ON COLUMN TEST_CASE.VERSION_NUMBER IS '버전 번호 (PUBLISHED 시 증가)';


-- 2. 테스트 시나리오 (시나리오 단위)
CREATE TABLE TEST_SCENARIO (
    SCENARIO_ID NUMBER PRIMARY KEY,
    CASE_ID NUMBER NOT NULL,
    SCENARIO_NAME VARCHAR2(500) NOT NULL,
    SCENARIO_ORDER NUMBER NOT NULL,  -- 시나리오 순서
    VERSION_STATUS VARCHAR2(20) DEFAULT 'DRAFT',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SCENARIO_CASE FOREIGN KEY (CASE_ID) REFERENCES TEST_CASE(CASE_ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_TEST_SCENARIO START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_SCENARIO_CASE ON TEST_SCENARIO(CASE_ID);

COMMENT ON TABLE TEST_SCENARIO IS '테스트 시나리오 (TEST CASE START 블록 단위)';


-- 3. 테스트 스텝 (Request/Expected 쌍)
CREATE TABLE TEST_STEP (
    STEP_ID NUMBER PRIMARY KEY,
    SCENARIO_ID NUMBER NOT NULL,
    CASE_NO VARCHAR2(10) NOT NULL,              -- 0001, 0002, ...
    STEP_ORDER NUMBER NOT NULL,                 -- 스텝 순서
    PRIORITY VARCHAR2(20) DEFAULT '보통',        -- HIGH, MEDIUM, LOW, 보통
    
    -- 📌 JSON 저장 (마이그레이션 용이)
    REQUEST_JSON CLOB NOT NULL,                 -- {"거래방법":"A", "requestMethodCode":"", ...}
    EXPECTED_JSON CLOB NOT NULL,                -- {"응답코드":"0000", "응답메시지":"정상", ...}
    
    VERSION_STATUS VARCHAR2(20) DEFAULT 'DRAFT',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT FK_STEP_SCENARIO FOREIGN KEY (SCENARIO_ID) REFERENCES TEST_SCENARIO(SCENARIO_ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_TEST_STEP START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_STEP_SCENARIO ON TEST_STEP(SCENARIO_ID);
CREATE INDEX IDX_STEP_CASE_NO ON TEST_STEP(CASE_NO);
CREATE INDEX IDX_STEP_VERSION ON TEST_STEP(VERSION_STATUS);

COMMENT ON TABLE TEST_STEP IS '테스트 스텝 (Request/Expected 쌍)';
COMMENT ON COLUMN TEST_STEP.REQUEST_JSON IS '요청 데이터 (JSON 형식으로 저장)';
COMMENT ON COLUMN TEST_STEP.EXPECTED_JSON IS '기대값 데이터 (JSON 형식으로 저장)';


-- ========================================
-- 📚 버전 관리 테이블
-- ========================================

-- 4. 버전 히스토리 (모든 변경 이력 보관)
CREATE TABLE TEST_CASE_HISTORY (
    HISTORY_ID NUMBER PRIMARY KEY,
    CASE_ID NUMBER NOT NULL,
    FILE_NAME VARCHAR2(255) NOT NULL,
    TITLE VARCHAR2(500) NOT NULL,
    NOTE CLOB,
    VERSION_NUMBER NUMBER NOT NULL,
    VERSION_TYPE VARCHAR2(20) NOT NULL,         -- AUTO_SAVE, MANUAL_SAVE, PUBLISH
    SNAPSHOT_JSON CLOB NOT NULL,                -- 전체 데이터 스냅샷 (JSON)
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR2(100) DEFAULT 'system',
    CHANGE_DESCRIPTION VARCHAR2(1000)           -- 변경 사유
);

CREATE SEQUENCE SEQ_TEST_CASE_HISTORY START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_HISTORY_CASE ON TEST_CASE_HISTORY(CASE_ID);
CREATE INDEX IDX_HISTORY_VERSION ON TEST_CASE_HISTORY(CASE_ID, VERSION_NUMBER);
CREATE INDEX IDX_HISTORY_DATE ON TEST_CASE_HISTORY(CREATED_AT);

COMMENT ON TABLE TEST_CASE_HISTORY IS '테스트 케이스 변경 이력';
COMMENT ON COLUMN TEST_CASE_HISTORY.VERSION_TYPE IS 'AUTO_SAVE: 자동저장(5분), MANUAL_SAVE: 임시저장, PUBLISH: 최종저장';
COMMENT ON COLUMN TEST_CASE_HISTORY.SNAPSHOT_JSON IS '해당 시점의 전체 데이터 스냅샷';


-- 5. 스텝 변경 추적 (diff 추적용)
CREATE TABLE TEST_STEP_CHANGE_LOG (
    LOG_ID NUMBER PRIMARY KEY,
    STEP_ID NUMBER,
    CASE_ID NUMBER NOT NULL,
    ACTION_TYPE VARCHAR2(20) NOT NULL,          -- INSERT, UPDATE, DELETE
    BEFORE_JSON CLOB,                           -- 변경 전 데이터
    AFTER_JSON CLOB,                            -- 변경 후 데이터
    CHANGED_FIELDS VARCHAR2(1000),              -- 변경된 필드 목록
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR2(100) DEFAULT 'system'
);

CREATE SEQUENCE SEQ_TEST_STEP_CHANGE_LOG START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_CHANGE_LOG_STEP ON TEST_STEP_CHANGE_LOG(STEP_ID);
CREATE INDEX IDX_CHANGE_LOG_CASE ON TEST_STEP_CHANGE_LOG(CASE_ID);

COMMENT ON TABLE TEST_STEP_CHANGE_LOG IS '스텝 변경 이력 (상세 diff 추적)';


-- ========================================
-- 📊 마이그레이션 지원 뷰
-- ========================================

-- 6. 전체 테스트 케이스 조회 뷰 (txt 파일 구조와 유사)
CREATE OR REPLACE VIEW V_TEST_CASE_FULL AS
SELECT 
    tc.CASE_ID,
    tc.FILE_NAME,
    tc.TITLE,
    tc.NOTE,
    tc.VERSION_STATUS,
    tc.VERSION_NUMBER,
    ts.SCENARIO_ID,
    ts.SCENARIO_NAME,
    ts.SCENARIO_ORDER,
    t.STEP_ID,
    t.CASE_NO,
    t.STEP_ORDER,
    t.PRIORITY,
    t.REQUEST_JSON,
    t.EXPECTED_JSON
FROM TEST_CASE tc
LEFT JOIN TEST_SCENARIO ts ON tc.CASE_ID = ts.CASE_ID
LEFT JOIN TEST_STEP t ON ts.SCENARIO_ID = t.SCENARIO_ID
ORDER BY tc.CASE_ID, ts.SCENARIO_ORDER, t.STEP_ORDER;


-- 7. DRAFT 버전만 조회 (편집용)
CREATE OR REPLACE VIEW V_TEST_CASE_DRAFT AS
SELECT * FROM V_TEST_CASE_FULL
WHERE VERSION_STATUS = 'DRAFT';


-- 8. PUBLISHED 버전만 조회 (실행용)
CREATE OR REPLACE VIEW V_TEST_CASE_PUBLISHED AS
SELECT * FROM V_TEST_CASE_FULL
WHERE VERSION_STATUS = 'PUBLISHED';


-- ========================================
-- 🔧 유틸리티 함수
-- ========================================

-- 9. 임시저장 → 최종저장 프로시저
CREATE OR REPLACE PROCEDURE PROC_PUBLISH_TEST_CASE (
    p_case_id IN NUMBER,
    p_user IN VARCHAR2 DEFAULT 'system',
    p_description IN VARCHAR2 DEFAULT NULL
) AS
    v_new_version NUMBER;
    v_snapshot CLOB;
BEGIN
    -- 현재 버전 +1
    SELECT NVL(MAX(VERSION_NUMBER), 0) + 1 
    INTO v_new_version
    FROM TEST_CASE_HISTORY
    WHERE CASE_ID = p_case_id;
    
    -- DRAFT → PUBLISHED 전환
    UPDATE TEST_CASE 
    SET VERSION_STATUS = 'PUBLISHED',
        VERSION_NUMBER = v_new_version,
        UPDATED_AT = CURRENT_TIMESTAMP,
        UPDATED_BY = p_user
    WHERE CASE_ID = p_case_id;
    
    UPDATE TEST_SCENARIO 
    SET VERSION_STATUS = 'PUBLISHED'
    WHERE CASE_ID = p_case_id;
    
    UPDATE TEST_STEP 
    SET VERSION_STATUS = 'PUBLISHED'
    WHERE SCENARIO_ID IN (SELECT SCENARIO_ID FROM TEST_SCENARIO WHERE CASE_ID = p_case_id);
    
    -- 히스토리에 스냅샷 저장 (JSON 형태로 전체 데이터 저장)
    SELECT JSON_OBJECT(
        'caseId' VALUE CASE_ID,
        'fileName' VALUE FILE_NAME,
        'title' VALUE TITLE,
        'note' VALUE NOTE
    ) INTO v_snapshot
    FROM TEST_CASE
    WHERE CASE_ID = p_case_id;
    
    INSERT INTO TEST_CASE_HISTORY (
        HISTORY_ID, CASE_ID, FILE_NAME, TITLE, NOTE, VERSION_NUMBER,
        VERSION_TYPE, SNAPSHOT_JSON, CREATED_BY, CHANGE_DESCRIPTION
    )
    SELECT 
        SEQ_TEST_CASE_HISTORY.NEXTVAL, CASE_ID, FILE_NAME, TITLE, NOTE, v_new_version,
        'PUBLISH', v_snapshot, p_user, p_description
    FROM TEST_CASE
    WHERE CASE_ID = p_case_id;
    
    COMMIT;
END;
/


-- 10. 자동 저장 프로시저 (5분마다)
CREATE OR REPLACE PROCEDURE PROC_AUTO_SAVE_TEST_CASE (
    p_case_id IN NUMBER,
    p_user IN VARCHAR2 DEFAULT 'system'
) AS
    v_snapshot CLOB;
BEGIN
    -- 현재 상태를 JSON 스냅샷으로 저장
    SELECT JSON_OBJECT(
        'caseId' VALUE CASE_ID,
        'fileName' VALUE FILE_NAME,
        'title' VALUE TITLE,
        'note' VALUE NOTE,
        'updatedAt' VALUE TO_CHAR(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
    ) INTO v_snapshot
    FROM TEST_CASE
    WHERE CASE_ID = p_case_id;
    
    INSERT INTO TEST_CASE_HISTORY (
        HISTORY_ID, CASE_ID, FILE_NAME, TITLE, NOTE, VERSION_NUMBER,
        VERSION_TYPE, SNAPSHOT_JSON, CREATED_BY
    )
    SELECT 
        SEQ_TEST_CASE_HISTORY.NEXTVAL, CASE_ID, FILE_NAME, TITLE, NOTE, VERSION_NUMBER,
        'AUTO_SAVE', v_snapshot, p_user
    FROM TEST_CASE
    WHERE CASE_ID = p_case_id;
    
    COMMIT;
END;
/


-- ========================================
-- 📝 샘플 데이터 (마이그레이션 참고용)
-- ========================================

-- 예시: test_case_1.txt 마이그레이션
INSERT INTO TEST_CASE (CASE_ID, FILE_NAME, TITLE, NOTE, VERSION_STATUS, VERSION_NUMBER)
VALUES (SEQ_TEST_CASE.NEXTVAL, 'test_case_1.txt', 'TestCase', 'Sample Test Case', 'DRAFT', 1);

INSERT INTO TEST_SCENARIO (SCENARIO_ID, CASE_ID, SCENARIO_NAME, SCENARIO_ORDER)
VALUES (SEQ_TEST_SCENARIO.NEXTVAL, 1, '주유소', 1);

-- Request: {"거래방법":"@", "requestMethodCode":"", "cancelYn":"", "원승인번호":""}
-- Expected: {"응답코드":"7834"}
INSERT INTO TEST_STEP (STEP_ID, SCENARIO_ID, CASE_NO, STEP_ORDER, PRIORITY, REQUEST_JSON, EXPECTED_JSON)
VALUES (
    SEQ_TEST_STEP.NEXTVAL, 
    1, 
    '0001', 
    1, 
    'LOW',
    '{"거래방법":"@","requestMethodCode":"","cancelYn":"","원승인번호":""}',
    '{"응답코드":"7834"}'
);

COMMIT;


-- ========================================
-- 🔍 유용한 쿼리
-- ========================================

-- 특정 케이스의 모든 스텝 조회 (편집 화면용)
/*
SELECT 
    ts.SCENARIO_NAME,
    t.CASE_NO,
    t.PRIORITY,
    t.REQUEST_JSON,
    t.EXPECTED_JSON,
    t.STEP_ORDER
FROM TEST_CASE tc
JOIN TEST_SCENARIO ts ON tc.CASE_ID = ts.CASE_ID
JOIN TEST_STEP t ON ts.SCENARIO_ID = t.SCENARIO_ID
WHERE tc.FILE_NAME = 'test_case_4.txt'
  AND tc.VERSION_STATUS = 'DRAFT'
ORDER BY ts.SCENARIO_ORDER, t.STEP_ORDER;
*/

-- 특정 케이스의 변경 이력 조회
/*
SELECT 
    VERSION_NUMBER,
    VERSION_TYPE,
    CREATED_AT,
    CREATED_BY,
    CHANGE_DESCRIPTION
FROM TEST_CASE_HISTORY
WHERE CASE_ID = 1
ORDER BY CREATED_AT DESC;
*/

-- 최근 변경된 케이스 목록
/*
SELECT 
    FILE_NAME,
    TITLE,
    VERSION_STATUS,
    VERSION_NUMBER,
    UPDATED_AT,
    UPDATED_BY
FROM TEST_CASE
ORDER BY UPDATED_AT DESC
FETCH FIRST 10 ROWS ONLY;
*/
